### ISSUE TITLE
Testing the software results in segmentation fault

### ISSUE THREAD

**Issue by telatin** [DMU-lilab/pTrimmer#1]
Hello,
I just compiled the software and tried to test with the data in Example with the command (ran from the repository base directory):
```bash
./pTrimmer-1.3.1 --seqtype pair --outdir ./out --read1 Example/data_R1.fq.gz --read2 Example/data_R2.fq.gz  --ampfile Example/data_amplicon.txt
```
results in 
```
Segmentation fault (core dumped)
```

Can you suggest me a testing command?
Is it possible to add some input check to avoid the segfault?

Thanks and best wishes

**Comment by davidlidl** [comment]
Andrea, thanks for your testing.  We will try to figure it out.  




--

网易VIP邮箱提醒：安全收发邮件，务必核实往来邮件地址、银行账号等机密信息，请通过电话或视频等多种方式确认信息真实性，提高警惕，请勿轻易透露个人重要信息。
Alert message of Netease Vipmail：Never provide your password, security questions, verification codes, or any other personal important information details to anyone else.
You can identify mail message by telephone,video-chat or other ways.You should make sure that your email address, bank account and other confidential information as secure as possible. Thank you for keeping your email account secure.

在 2019-05-22 21:08:52，"Andrea Telatin" <notifications@github.com> 写道：


Hello,
I just compiled the software and tried to test with the data in Example with the command (ran from the repository base directory):

./pTrimmer-1.3.1 --seqtype pair --outdir ./out --read1 Example/data_R1.fq.gz --read2 Example/data_R2.fq.gz  --ampfile Example/data_amplicon.txt

results in

Segmentation fault (core dumped)


Can you suggest me a testing command?
Is it possible to add some input check to avoid the segfault?

Thanks and best wishes

**Comment by XLZH** [comment]
The bug induced by the parameters parser has been fixed, please try it again. @telatin @davidlidl

**Comment by telatin** [comment]
Thanks, now it worked!
```
[*] Processing the [thread: 1] ...
[*] Processing the [thread: 2] ...
Total time consume: 0.0(s)

----------------- Summary ------------------------
Total reads processed: 500
Reads have bad primer: 39
Reads have bad quality: 0
Reads successfully trimed and have good quality: 92.20 %
```

As a very minor improvment for user experience, I'd check for the existence of output directory, as some tools want to create it and others (like this) expects to find one.
