### ISSUE TITLE
More informative debug output

### ISSUE THREAD

**Issue by jtremblay** [DMU-lilab/pTrimmer#13]
Dear pTrimmer developers,
First of all, thanks for writing this software. It is useful accurate and generally does a good job to remove primers in fastqs. Right now I am testing a new primer pair and the software crash with a segmentation fault error with no useful debug info. It would be much appreciated if you could include a more detailed debug output in standard error.
Regards,

**Comment by XLZH** [comment]
Thanks for your testing! @jtremblay

Could you please provide the following information so that I can figure out what's happened:

(1) The software version and platform you tested
(2) Post here the  primer pair and a few fastq lines that could reproduce the problem

Best wishes,
Xiaolong Zhang

**Comment by jtremblay** [comment]
Sure thing, 
The primer file is the following:
CAGCCGCGGTAATTCCAGCT	GAACCCAAACACTTTGGTTTCC	541

The fastq R1:
@M06648:114:000000000-JF3GP:1:1102:15213:1315#AAAAAAAAA/1
CAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAGAAGCTCGTAATTGAATTTCGAGACCGGTCTACTGGTCGTGCTTTTGTACGTACTGGTATAATCGGTTTCTCTCTTCTGACGAACTATAATGCCATTAATTTGGTGTTTTAGGGAATCAGGACTGTTACTTTGAAAAAATTAGAGTGTTTAAAGCAGGCTCACGCTTGAATACATTAGCAGGGAATAACGAAATATGACGTTTGATTTTATTGTGTTGGTTTCTAGGATCGACGTAAT
+
CCCCCGGEGGGGGGGGGGGGGGGFGGGGGGGGFFFGFFFFGDGGGGGGGGGGF9FGGGGGGGCFFEAFGGGGGFGG>GFGGGGFFGGEGGGGCF7FFF,CFGGGGGGGGFFDFCGG@FGGGGGGGFGGGFGGGGGDG,CFFFGG<<<EDGGGGGGGGGDFFGE,C<,333,CFA+8,C9;DEGFGGG9<BCD:>F9CEFBE,@;9=9>,>:EECFGGGD5:E,DD9:D9C:,,=5=5CGFGC?ECCC7;+2***;5+:CD>CCF+;=A**595C>DAF47C)7<5572)7
@M06648:114:000000000-JF3GP:1:1102:15232:1318#AAAAAAAAA/1
CAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAGAAGCTCGTAATTGAATTTCGAGACCGGTCTACTGGTCGTGCTTTTGTACGTACTGGTATAATCGGTTTCTCTCTTCTGACGAACTATAATGCCATTAATTTGGTGTTTTAGGGAATCAGGACTGTTACTTTGAAAAAATTAGAGTGTTTAAAGCAGGCTCACGCTTGAATACATTAGCATGGAATAACGAAATAGGACGTTTGATTTTATTTTGTTGGTTTCTAGGATCGACGTAAT
+
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGFGGGGGGGGGGGGGGGGGGGGGGFG<AFFGGGFGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGFGGDGGGGGFGGGGGGGGGGFGGGGGCCGGGGEG6EGECCFGGFGGG7FFDGGGADGCC,=FCEFGGGGAAGGGGGG@FC7AFFFGGDFGF74;FFF>FFFBFF

The fastq R2:
@M06648:114:000000000-JF3GP:1:1102:15213:1315#AAAAAAAAA/2
GAACCCAAACACTTTGGTTTCCCGTAAGGTGCCGAATGAGTCATTAATTTAACATCATCCGATCCCTAGTCGGCATAGTTTATGGTTAAGACTACGACGGTATCTGATCGTCTTCGATCCCCTAACTTTCGTTCTTGATTAATGAAAACATCCTTGGCAAATGCTTTCGCAGTAGTTAGTCTTCAATAAATCCAAGAATTTCACCTCTGACAATTGAATACTAATGCCCCCAACTATCCCTATTAATCATTACTTCGATCCTAGAAACCCAACAAATAAAATCAAAGGTA
+
CCCCCFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCFFGGGGGGGGGGGFGGGGFFGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGCGFGGFGGFG9ADGDGFFGGGGFG77:CFGFGGGA?FFFGGGGGFG++=,;:CCEDGG>EF)/8AEFC=868:CC**+-(+79E<3=A985)0(2:?18+4)));<@;)(.)
@M06648:114:000000000-JF3GP:1:1102:15232:1318#AAAAAAAAA/2
GAACCCAAACACTTTGGTTTCCCGTAAGGTGCCGAATGAGTCATTAATTTAACATCATCCGATCCCTAGTCGGCATAGTTTATGGTTAAGACTACGACGGTATCTGATCGTCTTCGATCCCCTAACTTTCGTTCTTGATTAATGAAAACATCCTTGGCAAATGCTTTCGCAGTAGTTAGTCTTCAATAAATCCAAGAATTTCACCTCTTACAATTGAATACTAATGCCCCCAACTATCCCTATTAATCATTACGTCGATCCTAAAAACCAACAAAATAAAATCAAACGAC
+
CCCCCGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGCFGGFGGGGGGGGGGGGGGFGGGGGGGGEGGGEGCGGGGGGGAFFGGGGGGFGGGGGDFGDCCGGGAEDFGG7CCDFFG?C<A7<2,BCCCFGGGGEG?791;5FF8@+9=1/9B*1(>)/-031)))))7*:AA6)2=@BB4)../;@E)((-

**Comment by jtremblay** [comment]
And the version I use is 1.3.3 (pTrimmer) and the OS is Centos7.

**Comment by XLZH** [comment]
Hi @jtremblay

I have checked the code and found that your read sequence is longer than 256bp, which induced the problem.

Therefore, I fixed the issue and added support for 512bp read sequence (a rational length) at most.
A new release of v1.3.4 is drafted on GitHub and passed your example files posted above.

By the way, I found that the length of sequence and corresponding quality are different in your example fastq lines, which may induced unexpected problems in your following analysis.

If you still have any question, please fell free to contact me, thanks for your support!

Best wishes,
Xiaolong Zhang

**Comment by jtremblay** [comment]
That's great thanks for the rapid solution @XLZH ! Much appreciated.
