### ISSUE TITLE
Feature Request: Compressed gz output

### ISSUE THREAD

**Issue by ammaraziz** [DMU-lilab/pTrimmer#24]
Hi there,

Thank you for creating and maintaining pTrimmer, fantastic tool.

It would be great to be able to output compressed gz trimmed fastq files. Unless I am mistaken this is not currently possible with pTrimmer.

Thanks,

Ammar

**Comment by XLZH** [comment]
@ammaraziz  Thank you very much for your suggestion. This will be particularly useful for some larger FASTQ files. I will add this feature as soon as possible, but it may take at least two weeks. Of course, if you urgently need to use this feature (e.g. your disk space is insufficient or your FASTQ files are too large), you can send me an email, and I will create a temporary version for you to support Gzip output.

**Comment by ammaraziz** [comment]
Dear @XLZH

Thank you for taking onboard this suggestions. Please do not rush on my behalf, I am very happy to hear you think this is a good idea and that you will implement it in the near future. 

Thank you again :)

**Comment by XLZH** [comment]
@ammaraziz 
Hello Ammar, The new feature that output gzipped trimmed fastq file has been implemented in pTrimmer-v1.4.0. Please refer to the Usage and Option sections for details. Thank you

best,
xiaolong zhang

**Comment by ammaraziz** [comment]
Amazing thank you. Let me test it out and report back.
