### ISSUE TITLE
empty sequence being added to trimmed fastqs

### ISSUE THREAD

**Issue by raphenya** [DMU-lilab/pTrimmer#3]
There are empty sequence being added to trimmed fastqs. I ran the following command:
```
pTrimmer-1.3.2 \
--seqtype pair \
--ampfile amplicon_file.txt \
--read1 R1_paired.fastq.gz \
--trim1 R1_ptrimmer.fastq \
--read2 R2_paired.fastq.gz \
--trim2 R2_ptrimmer.fastq \
--summary summary.ampcount
```

**Comment by XLZH** [comment]
Thaks for your testing!

So what kind of empty sequences are in the trimmed fastq file? Could you please post these kind of sequences here?

**Comment by raphenya** [comment]
### before running command (above)
```
$ grep @..........................:18471:1318 R1.fastq -A 3
@..........................:18471:1318 1:N:0:19
TAATACCTCGAGCTGTACCGTTGTTGCGCTGCCTAGATGCAGTGCTGCTCTTATCACATTTGCTTCGACGACTGCCGCCTTCGCTGTTTCCCTAGACACTCAACA
+
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```
```
$ grep @..........................:18471:1318 R2.fastq -A 3
@..........................:18471:1318 2:N:0:19
ATAAGCGCTTTTTGTAGGCAGGGGCACCC
+
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```



### after running command (above)
```
$ grep "@..........................:18471:1318" -A 3 R1.fastq 
@..........................:18471:1318 1:N:0:19
NNNNNNNNNNNNNNNNNNNN
+
!!!!!!!!!!!!!!!!!!!!
```
```
grep "@..........................:18471:1318" -A 3 R2.fastq 
@..........................:18471:1318 2:N:0:19

+
```

@XLZH Please not that I modified the sequences, device_id, and quality scores. Let me know if you need more information. Cheers.

**Comment by XLZH** [comment]
1. I think your read (18471:1318 2:N:0:19) is too short to match the primer sequence, because the read is usually longer than the longest primer sequence in your amplicon.txt
2. It does't matter to modify the device_id and quality scores (>minimum quality 20)
3. I suggest you use the original sequence when running the software pTrimmer

For more details of the primer removing algorithm, your can refer to the aritcle of pTrimmer (https://doi.org/10.1186/s12859-019-2854-x)

If you still have any questions, please feel free to contact me, thanks!

**Comment by raphenya** [comment]
@XLZH Just to be sure that the `amplicon_file.txt` I used is correct how would I convert the following primer information to `amplicon_file.txt`:

| Primer_Name        | Sequence           | Length  | Start | End | Amplicon_size|
| ------------- |:-------------:| :-------------:| :-------------:| :-------------:|-----:|
| primer1_left      | AAAAAAAAAAAAAAAAAAAAAA | 22 | 100| 122|  300|
| primer2_right      | AAAAAAAAAAAAAAAAAAAA     |   20 | 800 | 600 | - |

**Comment by XLZH** [comment]
@raphenya You can also refer to the example amplicon file of "pTrimmer/Example/data_amplicon.txt".

        One Amplicon example as follows:

        forward primer(22bp)                                   reverse primer(20bp)
        ++++++++++++++++++=====================================++++++++++++++++++
        |                 |                                   |                 |
    ampstart         insertstart                         insertend            ampend
     (100)              (122)                               (380)              (400)


    amplicon_file.txt as follows:

    #FowrdPrimer<TAB>ReversePrimer<TAB>InsertLength<TAB>AuxInfo
    AAAAAAAAAAAAAAAAAAAAAA<TAB>AAAAAAAAAAAAAAAAAAAA<TAB>258<TAB>Amplicon1

    Note:
    1. The amplicon size is 300bp in this example
    2. forward primer: like your primer1_left
    3. reverse primer: like your primer2_right (I guss there is somthing wrong with your position of primer2_right)
    4. InsertLength: insertend - insertstart + 1
    5. AuxInfo: the amplicon name or something else

**Comment by smzt** [comment]
Dear developers,
Is it possible that the software discards paired reads where both primers are not found? If the amplicon is large, then some of the reads will not have the opposite primer at the 3'-end or if they have it, they might have just a small part. 
One of my amplicos is being completely missed and NNNNN are reported in the final files. Here are 3 reads for that amplicon (paired-end).

r1.fastq
-----------
@M03970:332:000000000-J2CK5:1:1101:16151:2887 1:N:0:15
GTCCAGCTTTGTGCCAGGAGCCTCGCAGGGGTTGATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACA
+
>>AABFCFDDFFGFGGGGGAGFHFEGG2A2AEEG3FFG2GFHFHGE1AEEHHHHHGGGHH3FDFHHHHHHHEGHGGFGGGH3FFFBFFC?BGFHHHHEGHHFFDH?FHGHH2B?G/?<GGFFG//FC@2<FFGGHHBDGHHGD//--><
@M03970:332:000000000-J2CK5:1:1101:21721:3033 1:N:0:15
GTCCAGCTTTGTGCCAGGAGCCTCGCAGGGGTTGATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACA
+
BBCCCFFFFFFFGGGGGGGGGGHHGGCFGEEEEGHHHHHHHHHHHGGGGGHHHHHGGGHHHHHHHHHHHHHHHHHGGGGGFHHHHHHHGGHHHHHHHHHFHHHHHHHHHHHHHGHGGGHHGGGGHGHFGHHHHHHHCEHHHGGGGGGGG
@M03970:332:000000000-J2CK5:1:1101:14369:3115 1:N:0:15
GTCCAGCTTTGTGCCAGGAGCCTCGCAGGGGTTGATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGCCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACA
+
CCCCCFFFFFFFGGGGGGGGGGHHGGGGGGGGGGHHHHHHHHHHHGGGGGHHHHHGGGHHHHHHHHHHHHHHHHHGGGGGHHHHHHHHGGHHHHHHHHHHHHHHHHHHHHHHHGHGGGHHGGGGHHH@FGHHHHHHHGHHHGGGGGGGG

r2.fastq
---------

@M03970:332:000000000-J2CK5:1:1101:16151:2887 2:N:0:15
AGCCCGAACGCAAAGTGTCCCCGGAGCCCAGCAGCTACCTGCTCCCTGGACGGTGGCTCTAGCCTTTTGAGAAGCTCAAAACTTTTAGCGCCAGTCTTGAGCACATGGGAGGGGAACACCCCAATCCCATCAACCCCTGCGAGGCTACTGG
+
?AA@ADDDDDADG?BGG3FGGGGE0/AFE/EFB0GF1FFDDHBGHGFCG0BE/>EEHCGF1B1B@11B1//>B0F1G1@11BFFGD2>GEGGCEBFHEFFBFHFH1F0/0?CCC///<@EGG?/FFHHFHHF1FGGGE..<<<-CC0<:CG
@M03970:332:000000000-J2CK5:1:1101:21721:3033 2:N:0:15
AGCCCGAACGCAAAGTGTCCCCGGAGCCCAGCAGCTACCTGCTCCCTGGACGGTGGCTCTAGACTTTTGAGAAGCTCAAAACTTTTAGCGCCAGTCTTGAGCACATGGGAGGGGAAAACCCCAATCCCATCAACCCCTGCGAGGCTCCTGG
+
ABBBBB?ADDBB?CGGGGGGGGGGGGGGGFFHHHHHGHHHGHHHHGHHHBHGGEHGHHHHBG4FFHHHHAF?4BFHHB@@3FGHHH4EGGGGGGGHHHHDHHHHFGFHGGFGGGGG/FHGGGA/GHHHFHH11GGGGGGHGCDCG.CGHGH
@M03970:332:000000000-J2CK5:1:1101:14369:3115 2:N:0:15
AGCCCGAACGCAAAGTGTCCCCGGAGCCCAGCAGCTACCTGCTCCCTGGACGGTGGCTCTAGGCTTTTGAGAAGCTCAAAACTTTTAGCGCCAGTCTTGAGCACATGGGAGGGGAAAACCCCAATCCCATCAACCCCTGCGAGGCTCCTGG
+
AB@AABBBBBBBGGFGFGGGGGGGCGGGGHHHHGHHHHHHHHHHHGHHHHHGGEGDHHHHFHHHHHHFHFGHHHHHHHFFFHHHHHHHHGGGGGHHHHHHHHHHHHHHGHGGGGGGHHHGGGGGHHHHHHHHHHHGGGGHGGGGGFHGHHH

Primers used to amplify the region:
------------
>TP53_Ex1_a_5
GTCCAGCTTTGTGCCAGGAG
>TP53_Ex1_a_3
AGCCCGAACGCAAAGTGT


amplicon_primers.txt
-----------------------------
AGCCCGAACGCAAAGTGT      GTCCAGCTTTGTGCCAGGAG    125


Thanks very much in advance.

Regards,

Sheila

**Comment by XLZH** [comment]
Hello  @smzt,

pTrimmer supports both "long amplicon size (normal condition)" and "short amplicon size (read-through condition)".
The amplicon you provided, in fact, is the "read-through condition". But the opposite primer at the 3'-end is too short (even shorter than one kmer length) to be located! To obtain accurate results, we prefer to discard such reads.

The match condition of your read is as follows:
fastq1: opposite primer at  3'-end only has 3 bases (ACA)
fastq2: opposite primer at  3'-end only has 7 bases (CTCCTGG)


    ----- fastq 1 -----
    @M03970:332:000000000-J2CK5:1:1101:16151:2887 1:N:0:15
    GTCCAGCTTTGTGCCAGGAG CCTCGCAGGGGTTGATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGG ACA
    GTCCAGCTTTGTGCCAGGAG                                                                                                                                ACACTTTGCGTTCGGGCT

    ----- fastq 2 -----
    @M03970:332:000000000-J2CK5:1:1101:21721:3033 2:N:0:15
    AGCCCGAACGCAAAGTGT CCCCGGAGCCCAGCAGCTACCTGCTCCCTGGACGGTGGCTCTAGACTTTTGAGAAGCTCAAAACTTTTAGCGCCAGTCTTGAGCACATGGGAGGGGAAAACCCCAATCCCATCAACCCCTGCGAGG CTCCTGG
    AGCCCGAACGCAAAGTGT                                                                                                                                CTCCTGGCACAAAGCTGGAC
