### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by marchoeppner** [DMU-lilab/pTrimmer#5]
Hi,

thanks for this interesting tool!

However, the documentation on git seems to be very out of date. The option for seqtype is no longer "-t", but "-s", the option to name the output files is gone and instead the option for the output directory is now mandatory (-o). The naming convention of the output files is not documented (which it probably should be).

/M

**Comment by XLZH** [comment]
Hi Marc,

I think the software you use is version 1.3.1, but the README in the GitHub now is version1.3.2.
So I suggest you use the version1.3.2, which allow you to specify the output file flexibly.

Best,
Xiaolong

**Comment by marchoeppner** [comment]
Thank you for the explanation, I kind of assumed that the version on Bioconda would be up to date. Closing this.
