### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by FelixMoelder** [DMU-lilab/pTrimmer#8]
Would you create a new release so a new build including macOS can be made available on Bioconda?

**Comment by XLZH** [comment]
I found a new release(v1.3.2) has been available on the bioconda now. Thanks~
url: https://anaconda.org/bioconda/ptrimmer

**Comment by FelixMoelder** [comment]
That's right. But release v1.3.2 only supports linux systems as macOS support has been merged afterwards. To add a macOS version on bioconda it would be necessary to create a new github release of the current master.

**Comment by XLZH** [comment]
Okay, Thank you for your reminder!

**Comment by FelixMoelder** [comment]
Thank's for updating. The new release is now available on bioconda.
